export const NAV_LINKS = [
  { labelKey: 'home', href: '#hero' },
  { labelKey: 'about', href: '#about' },
  { labelKey: 'experience', href: '#experience' },
  { labelKey: 'events', href: '#events' },
  { labelKey: 'projects', href: '#projects' },
  { labelKey: 'skills', href: '#skills' },
  { labelKey: 'education', href: '#education' },
  { labelKey: 'contact', href: '#contact' },
]

export const GITHUB_URL = 'https://github.com/ozcannrabia'
export const LINKEDIN_URL = 'https://linkedin.com/in/rabia-ozcan35'

export const PROJECTS = [
  {
    id: 1,
    title_tr: 'CV AI Scanner | AI Destekli Kariyer Analizi',
    title_en: 'CV AI Scanner | AI-Powered Career Analysis',
    description_tr: 'Google Gemini API entegrasyonu ile gerçek zamanlı CV analizi ve kişiselleştirilmiş kariyer geri bildirimi sunan mobil uygulama. "Glassmorphism" tasarım dili ile modern kullanıcı arayüzü geliştirildi.',
    description_en: 'A mobile application providing real-time CV analysis and personalized career feedback via Google Gemini API integration. Modern UI developed using the "Glassmorphism" design language.',
    images: ['images/cv-ai-scanner.jpg', 'images/cv-ai-scanner-2.jpg'],
    color: '#8c52ff',
    tags: ['Mobile', 'Google Gemini API', 'AI', 'Glassmorphism', 'Figma'],
    demo: '#',
    github: GITHUB_URL,
    featured: true,
  },
  {
    id: 2,
    title_tr: 'BiP Social Arena | Turkcell CodeNight',
    title_en: 'BiP Social Arena | Turkcell CodeNight',
    description_tr: 'Kullanıcı etkileşimlerini analiz eden; challenge tabanlı puanlama, rozet sistemi ve liderlik tablosu mekanikleri içeren sosyal etkileşim platformu.',
    description_en: 'A social interaction platform that analyzes user interactions with challenge-based scoring, badge system, and leaderboard mechanics.',
    images: [
  'images/bip-social-arena.jpg',
  'images/bip-social-arena-2.jpg',
  'images/bip-social-arena-3.jpg',
  'images/bip-social-arena-4.jpg',
  'images/bip-social-arena-5.jpg',
  'images/bip-social-arena-6.jpg',
  'images/bip-social-arena-7.jpg',
  'images/bip-social-arena-8.jpg',
],
    color: '#00d4ff',
    tags: ['Python', 'FastAPI', 'React 18', 'SQLite', 'Pandas'],
    demo: '#',
    github: GITHUB_URL,
    featured: true,
  },
  {
    id: 3,
    title_tr: 'Catify | Barınak Yönetim Sistemi',
    title_en: 'Catify | Animal Shelter Management System',
    description_tr: 'Hayvan barınaklarının operasyonel süreçlerini (bağış takibi, gönüllü yönetimi, finansal raporlama) optimize etmek için geliştirilen uçtan uca yönetim sistemi.',
    description_en: 'An end-to-end management system to optimize animal shelter operations including donation tracking, volunteer management, and financial reporting.',
   images: [
  'images/catify.jpg',
  'images/catify-2.jpg',
  'images/catify-3.jpg',
  'images/catify-4.jpg',
  'images/catify-5.jpg',
  'images/catify-6.jpg',
  'images/catify-7.jpg',
],
    color: '#ff6b6b',
    tags: ['JavaScript', 'Node.js', 'Express.js', 'MySQL', 'HTML/CSS'],
    demo: '#',
    github: GITHUB_URL,
    featured: false,
  },
  {
    id: 4,
    title_tr: 'Superstep | Satış & Müşteri Analiz Paneli',
    title_en: 'Superstep | Sales & Customer Analysis Dashboard',
    description_tr: 'Perakende verilerini görselleştiren, KPI takibi ve müşteri segmentasyonu yoluyla veri odaklı karar destek mekanizması sunan dashboard uygulaması.',
    description_en: 'A dashboard visualizing retail data, offering data-driven decision support through KPI tracking and customer segmentation.',
    images: [
  'images/superstep.jpg',
  'images/superstep-1.jpg',
  'images/superstep-2.jpg',
  'images/superstep-3.jpg',
  'images/superstep-4.jpg',
  'images/superstep-5.jpg',
  'images/superstep-6.jpg',
  'images/superstep-7.jpg',
  'images/superstep-8.jpg',
  'images/superstep-9.jpg',
  'images/superstep-10.jpg',
],
    color: '#00ff9f',
    tags: ['JavaScript', 'Chart.js', 'Python', 'SQL', 'Data Visualization'],
    demo: '#',
    github: GITHUB_URL,
    featured: false,
  },
  {
    id: 5,
    title_tr: 'MIS Chatbot & Meslek Karşılaştırma',
    title_en: 'MIS Chatbot & Career Comparison',
    description_tr: "YBS öğrencilerinin kariyer yollarını incelemesine olanak tanıyan, doğal dil işleme tabanlı karşılaştırma sistemi. (MII'25 Sunumu)",
    description_en: "A natural language processing-based system enabling MIS students to explore career paths. (MII'25 Presentation)",
    images: ['images/mis-chatbot.jpg', 'images/mis-chatbot-2.jpg'],
    color: '#f7a14a',
    tags: ['HTML', 'CSS', 'Python', 'NLP', 'Data Analysis'],
    demo: '#',
    github: GITHUB_URL,
    featured: false,
  },
  {
    id: 6,
    title_tr: 'Manjog | UX Odaklı Mobil Uygulama',
    title_en: 'Manjog | UX-Focused Mobile App',
    description_tr: 'İnsan-Bilgisayar Etkileşimi (HCI) teorileri temel alınarak tasarlanan kullanıcı merkezli arayüz. Figma üzerinden kapsamlı UI Kit geliştirme süreci yürütüldü.',
    description_en: 'A user-centric interface designed based on HCI theories. A comprehensive UI Kit development process was carried out via Figma.',
    images: [
  'images/manjog.jpg',
  'images/manjog-2.jpg',
  'images/manjog-3.jpg',
],
    color: '#ff9f43',
    tags: ['Figma', 'UX Research', 'HCI', 'UI Kit', 'Prototyping'],
    demo: '#',
    github: GITHUB_URL,
    featured: false,
  },
  {
    id: 7,
    title_tr: 'Algoritmik Trading Stratejisi | Paribu CodeNight',
    title_en: 'Algorithmic Trading Strategy | Paribu CodeNight',
    description_tr: 'Python ile geçmiş veriye dayalı, teknik indikatörler kullanan ve backtesting ile test edilen bir trading stratejisi geliştirildi.',
    description_en: 'A trading strategy built with Python using historical data, technical indicators, and validated through backtesting.',
    images: [
  'images/trading-strategy.jpg',
  'images/trading-strategy-2.jpg',
  'images/trading-strategy-3.jpg',
  'images/trading-strategy-4.jpg',
],
    color: '#ffd32a',
    tags: ['Python', 'Pandas', 'Trading', 'Backtesting', 'Technical Analysis'],
    demo: '#',
    github: GITHUB_URL,
    featured: false,
  },
]

export const EDUCATION = [
  {
    id: 1,
    degree_tr: 'Yönetim Bilişim Sistemleri (YBS)',
    degree_en: 'Management Information Systems (MIS)',
    school: 'Dokuz Eylül Üniversitesi',
    year: 'Eyl 2022 – Haz 2027',
    extra: 'GPA: 2.92',
    description_tr: 'İş süreçleri ve teknolojinin kesişiminde eğitim alıyorum. Coğrafi bilgi sistemleri, karar destek sistemleri, veritabanı yönetimi, yazılım geliştirme ve dijital proje yönetimi alanlarında dersler içermektedir.',
    description_en: 'Studying at the intersection of business processes and technology. Coursework covers GIS, decision support systems, database management, software development, and digital project management.',
    icon: '🎓',
  },
  
]

export const SOCIALS = [
  { name: 'GitHub', href: GITHUB_URL, icon: 'GH' },
  { name: 'LinkedIn', href: LINKEDIN_URL, icon: 'LI' },
  { name: 'Email', href: 'mailto:rabiaozcann02@gmail.com', icon: '@' },
]
